Repository DS-Studify/front-end, pull requests merged in 2025-09, with the labels that each got.

#81 [fix] 1차 QA 피드백 반영
  app/src/main/java/com/ds/studify/ui/MainScreen.kt
  core/ui-extension/src/main/java/com/ds/studify/core/ui/extension/Utils.kt
  feature/camera/src/main/java/com/ds/studify/feature/camera/CameraSreen.kt
  feature/statistics/src/main/java/com/ds/studify/feature/calendar/StatsScreen.kt
  feature/statistics/src/main/java/com/ds/studify/feature/calendar/navigation/StatsNavigation.kt
Labels: 🐛 Bug, 🎨 Design

#85 [feature] 회원 탈퇴 api 연결
  app/src/main/java/com/ds/studify/navigation/StudifyNavHost.kt
  core/data/src/main/java/com/ds/studify/core/data/datasource/UserDataSource.kt
  core/data/src/main/java/com/ds/studify/core/data/repository/UserRepository.kt
  core/data/src/main/java/com/ds/studify/core/data/repository_impl/UserRepositoryImpl.kt
  core/data/src/main/java/com/ds/studify/core/data/service/UserService.kt
  core/resources/src/main/res/drawable-xxxhdpi/ic_account_deletion.png
  core/resources/src/main/res/values/strings.xml
  feature/mypage/src/main/java/com/ds/studify/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/ds/studify/feature/mypage/MyPageViewModel.kt
  feature/mypage/src/main/java/com/ds/studify/feature/mypage/component/AccountDeletionModal.kt
  feature/mypage/src/main/java/com/ds/studify/feature/mypage/navigation/MypageNavigation.kt
Labels: 🎨 Design, 📭 API

#87 [feat] 회원 정보 약관 추가
  app/src/main/java/com/ds/studify/navigation/StudifyNavHost.kt
  core/resources/src/main/res/values/strings.xml
  feature/signup/src/main/java/com/ds/studify/feature/signup/SignupScreen.kt
  feature/signup/src/main/java/com/ds/studify/feature/signup/SignupViewModel.kt
  feature/signup/src/main/java/com/ds/studify/feature/signup/TermsWebViewScreen.kt
  feature/signup/src/main/java/com/ds/studify/feature/signup/navigation/SignupNavigation.kt
Labels: ✨ Feature

#89 [feat] 앱 아이콘 추가
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/ic_launcher_background.xml
  feature/analysis/src/main/java/com/ds/studify/feature/analysis/AnalysisScreen.kt
Labels: 🎨 Design
